# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "content" ]
  pull_request:
    branches: [ "content" ]

permissions:
  contents: read
  render: read
  view: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: render
        fetch-depth: 1
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip wheel
    - name: Bootstrap
      run: make bootstrap
    - name: Fetch content
      run: make fetch
    - name: Build
      run: make
    - name: Publish
      run: make publish
