name: render content to view

on:
  push:
    branches: [ "content" ]
  pull_request:
    branches: [ "content" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: render
        path: render
    - uses: actions/checkout@v3
      with:
        ref: content
        path: content
    - name: Sync content
      run: rsync -a content render
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip wheel
    - name: Bootstrap
      run: cd render && make bootstrap
    - name: Build
      run: cd render && make
    - name: Publish
      run: cd render && make publish
