name: render content to view

on:
  push:
    branches: [ "content" ]
  pull_request:
    branches: [ "content" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: render
        path: render
    - uses: actions/checkout@v3
      with:
        ref: content
        path: content
    - name: Sync content
      run: rsync -a --exclude=.git content/ render
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -qq -y update
        sudo -E apt -qq -y install slimit
        python3 -m pip install --upgrade pip wheel
    - name: Build and Publish
      run: |
        pushd render
          python3 -m pip install -U -r requirements.txt
          mkdir -p output
          pelican -s pelican/settings.py -o output content
        popd
