name: render content to view

on:
  push:
    branches: [ "content" ]
  pull_request:
    branches: [ "content" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: render
        path: render
    - uses: actions/checkout@v3
      with:
        ref: content
        path: content
    - name: Sync content
      run: |
        ls -lh content
        ls -lh render
        rsync -av content render
        ls -lh render
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip wheel
    - name: Build and Publish
      run: |
        pushd render
          python3 -m pip install -U -r requirements.txt
          PELICAN=pelican make build
          make publish
        popd
