name: render content to view

on:
  push:
    branches: [ "content" ]
  pull_request:
    branches: [ "content" ]

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: render
        path: render
    - uses: actions/checkout@v3
      with:
        ref: content
        path: content
    - name: Sync content
      run: rsync -a --exclude=.git content/ render
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: python3 -m pip install --upgrade pip wheel
    - name: Build and Publish
      run: |
        pushd render
          python3 -m pip install -U -r requirements.txt
          mkdir -p output
          pelican -s pelican/settings.py -o output content
        popd
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: render/output
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
