name: render content to view

on:
  push:
    branches: [ "content" ]
  pull_request:
    branches: [ "content" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: render
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip wheel
    - name: Bootstrap
      run: make bootstrap
    - name: Fetch content
      run: make fetch
    - name: Build
      run: make
    - name: Publish
      run: make publish
